### ISSUE TITLE
API v9?

### ISSUE THREAD

**Issue by Exr0n** [icepuma/fbtoggl#3]
Looks like an awesome project, I'm looking to use this in a Toggl Track client of my own...

Do you have plans to update to the v9 API? It [sounds like they're going to be phasing out v8 soon...](https://toggl.com/blog/toggl-track-api-v9)

If not, I might make a fork

Cheers!

**Comment by icepuma** [comment]
Hey,
I'm aware of their phase out. Their new documentation is not complete, neither was their old one. I contacted them and said, that I will wait till the documentation is complete.

I will contact them the coming days, as I'm pretty busy right now to see what happened in regards of the missing fields.

Best
Stefan

**Comment by icepuma** [comment]
Sadly the documentation is that bad, that I have to reverse engineer everything via yolo & error.

**Comment by icepuma** [comment]
I more or less migrated to the new API v9. I will test everything tomorrow and bake a release afterwards.

**Comment by icepuma** [comment]
If you experience any problems, please hit me up with a new issue.

Cheers!
